# https://www.getzola.org/documentation/getting-started/configuration/
base_url = "https://nakamochi.io"
# default page meta title and <title/> suffix
title = "nakamochi"
# appears in all pages metadata
description = "a simple to use bitcoin and lightning node for anyone and everyone"
default_language = "en"

output_dir = "output"
compile_sass = true
build_search_index = false
ignored_content = []

[markdown]
highlight_code = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

# custom variables accessible at config.extra in templates
[extra]
sitenav = [
  {path = "@/source.md", en = "sources", de = "quellcode", it = "sorgenti"},
  {path = "@/about.md", en = "about", de = "about", it = "about"},
]

[translations]
not_found = "not found"
foot_license = """\
    except where otherwise noted, content on this site is licensed under a \
    <a href="https://creativecommons.org/licenses/by/4.0/" rel="license noreferrer noopener">\
    CC BY 4.0</a> license.\
    """

# language translations
[languages.de]
title = "nakamochi"
description = "eine einfache Bitcoin und Lightning Node für alle"
[languages.de.translations]
not_found = "nichts gefunden"
foot_license = """\
    soweit nicht anders angegeben, stehen die Inhalte dieser Seite unter einer \
    <a href="https://creativecommons.org/licenses/by/4.0/deed.de" rel="license noreferrer noopener">\
    CC BY 4.0</a> Lizenz.\
    """

[languages.it]
title = "nakamochi"
description = "un nodo bitcoin e lightning semplice da usare per tutti"
[languages.it.translations]
not_found = "pagina non trovata"
foot_license = """\
    su questo sito tutti i contenuti sono pubblicati secondo le norme della licenza \
    <a href="https://creativecommons.org/licenses/by/4.0/deed.it" rel="license noreferrer noopener">\
    CC BY 4.0</a>, ad eccezione dei casi in cui siano esplicitamente indicate altre condizioni di uso.\
    """
